---
- hosts: localhost
  tasks:
    - name: Create a role with description
      iam_role:
        name: mynewrole
        assume_role_policy_document: "{{ lookup('file','policy.json') }}"
        managed_policy:
          - arn:aws:iam::aws:policy/PowerUserAccess
          - arn:aws:iam::aws:policy/AmazonEC2FullAccess
