---
- hosts: localhost
  tasks:
    - name: Create a role with description
      iam_role:
        name: mynewrole
        assume_role_policy_document: "{{ lookup('file','policy.json') }}"
        state: absent
