---
- hosts: localhost
  tasks:
    - name: install java
      shell: sudo yum install java-1.8.0-openjdk -y

    - name: install openjdk11
      shell: sudo amazon-linux-extras install java-openjdk11

    - name: install git
      shell: sudo yum install git -y

    - name: install wget
      shell: sudo yum install wget -y

    - name: Download maven repo
      shell: sudo wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo -O /etc/yum.repos.d/epel-apache-maven.repo
    
    - name: sed maven repo  
      shell: sudo sed -i s/\$releasever/6/g /etc/yum.repos.d/epel-apache-maven.repo
    
    - name: install maven 
      shell: sudo yum install -y apache-maven

    - name: install apache
      shell: sudo yum install httpd -y
    
    - name: start apache  
      shell: sudo systemctl start httpd
    
    - name: enable apache
      shell: sudo systemctl enable httpd

    - name: install epel
      shell: sudo amazon-linux-extras install epel -y
    
    - name: download jenkins repo
      shell: sudo wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
    
    - name: import jenkins io key
      shell: sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
    
    - name: install jenkins
      shell: sudo yum -y install jenkins
    
    - name: start jenkins
      shell: sudo systemctl start jenkins
    
    - name: enable jenkins
      shell: sudo systemctl enable jenkins

    - name: install utilis for terraform
      shell: sudo yum install -y yum-utils
    
    - name: terraform add repo
      shell: sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
    
    - name: install terraform
      shell: sudo yum -y install terraform
